### ISSUE TITLE
[OEP-001] Add a POST API to 'Register' new Institutes in Portal 

### ISSUE THREAD

**Issue by nitishhurduke** [nitishhurduke/online_exam_portal#1]
1. **POST** API with `/register` mapping should be added under `/institutes` in `InstitutesController`
2. In Database `institute` table  should reflect registered institutes.
3. Institute Repository and Service are added and working ass expected for this **POST** request.
4. Update `InstituteUtils `with generic functions required to process Institute activities.
5. the API should handle requestBody in format 
      >  {
      >   "name": "ssdf",
      >   "contactNo": 213422234,
      >   "address": "Aurangabad",
      >   "emailId": "example@mail.com",
      >   "password": "dfgdfg"
      > }
6. Passwords to be encypted before stored in database.

**Comment by nitishhurduke** [comment]
Hi @ajayl83, I am already working on It,  Thanks for showing interest in this project though, I will create subsequent issues to this, Let me know if you want to contribute in them.

**Comment by ajayl83** [comment]
@nitishhurduke Sure happy to help!
